### ISSUE TITLE
Can't make it work with Zoom

### ISSUE THREAD

**Issue by kristijanhusak** [jikamens/bt_pa_auto_switcher#2]
Hi,

I'm trying to set up this with [Zoom](https://zoom.us), but I can't manage to make it work.
I added the zoom to the valid clients list, and it detects it, but it doesn't really switch the type.

This is how I added the client:
```diff
diff --git a/bt_pa_auto_switcher.pl b/bt_pa_auto_switcher.pl
index abd602c..2d87353 100755
--- a/bt_pa_auto_switcher.pl
+++ b/bt_pa_auto_switcher.pl
@@ -155,7 +155,7 @@ use File::Basename;
 $ENV{"LC_ALL"} = "C";
 
 # WEBRTC VoiceEngine is Google Chat, Voice, and Talk.
-my $valid_clients = qr/(?:Skype|WEBRTC VoiceEngine|Google Chrome(?: input)?)/;
+my $valid_clients = qr/(?:Skype|ZOOM VoiceEngine|WEBRTC VoiceEngine|Google Chrome(?: input)?)/;
 my $mute_corked = 1;
 my $whoami = basename $0;
 my $verbose = 0;
```

And this is the output I get when I open up zoom and go to Audio settings:
```
kristijan [~/github/bt_pa_auto_switcher] at  master !
→ ./bt_pa_auto_switcher.pl
pacmd list-source-outputs
bt_pa_auto_switcher.pl: good client (source-output, 62): ZOOM VoiceEngine
bt_pa_auto_switcher.pl: NEW: source-output / 62 / ZOOM VoiceEngine
```
Once it printed this out, I went to blueman-manager to see if it really switched the type, but it didn't.
Also, i didn't had the option in Zoom audio settings to select the bluetooth headset, which properly appears if i manually switch type from blueman-manager.

Do you have any suggestions how can I make this work?

Thanks!

**Comment by jikamens** [comment]
Can you try the version I just pushed and see if it works better for you?

**Comment by kristijanhusak** [comment]
Yeah, unfortunately it's still not working.

**Comment by jikamens** [comment]
One more time with the newest version?

I'm sorry to have to ask you to keep testing, but unfortunately although I'm finding problems as I debug this, I'm not sure the problems I'm finding are the problem you're running into.

One caveat: as noted in the comment I added in the current version, sometimes ZOOM stays connected to the speaker and microphone even when it's not in the middle of a call. When this happens there's nothing my script can do to detect it and switch back to A2DP, since as far as it can tell ZOOM is using the microphone so it needs to be in HSP.

You can tell that this is happening if you open the Settings app and look at the Sound settings and "ZOOM VoiceEngine" shows up in the "Volume Levels" list with a little microphone icon.

In this case, all you can do to get the script to switch back to A2DP is tell the Zoom client to exit.

**Comment by kristijanhusak** [comment]
I will test it on Monday, since I'm using bluetooth headset only in office. 
No worries, thank you for responding and acting on this so fast.

**Comment by kristijanhusak** [comment]
Sorry for the late response, wasn't able to test it earlier.
Everything looks good, it properly switches to the HSP once I join the meeting. Thanks!
